name: my-python-packages
channels:
  - conda-forge
dependencies:
  - python=3.9  # or your preferred Python version
  - numpy
  - pandas
  - matplotlib
  - streamlit
  - wordcloud
  - plotly
  - scikit-learn
  - networkx
  - re
  - pip
  - pip:
      - bertopic
      - vaderSentiment
